### ISSUE TITLE
Missing kicad library symbols

### ISSUE THREAD

**Issue by fadushin** [fgervais/esp32-wrover-breakout#2]
I am unable to view all symbols in the esp32-rover-breakout.sch schematic.  The `kicad-library` directory appears to be empty on `master`, but the shematic file is searching there for several symbols (such as WROVER)

**Comment by fgervais** [comment]
Thank you for you interest in this project @fadushin, it could be because the clone was not recursive, the command would be:

```
git clone --recursive git@github.com:fgervais/esp32-wrover-breakout.git
```

**Comment by fadushin** [comment]
Thank you!
